-- 🧭 V19__admin_features.sql
-- 관리자 시스템: 대시보드 통계 및 제휴 상품 관리용 테이블

-- 1. 관리자 대시보드 일별 통계 테이블
CREATE TABLE admin_daily_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stats_date DATE NOT NULL UNIQUE,          -- 집계 날짜
    total_users INTEGER NOT NULL DEFAULT 0,    -- 총 이용자 수
    total_dentists INTEGER NOT NULL DEFAULT 0, -- 총 제휴 치과 수
    new_inquiries INTEGER NOT NULL DEFAULT 0,  -- 신규 문의 건수
    weekly_usage INTEGER NOT NULL DEFAULT 0,   -- 최근 7일(월~일) 누적 이용 건수
    user_trend DECIMAL(5, 2) DEFAULT 0.00,     -- 전일 대비 이용자 증가율 (%)
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 2. 제휴 치과 전용 상품 관리 테이블
CREATE TABLE partner_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL,            -- 칫솔류, 치약 및 세정제, 치간, 혀 및 구강, 특수케어, 기타
    name VARCHAR(255) NOT NULL,               -- 제품명
    price INTEGER NOT NULL,                   -- 가격
    manufacturer VARCHAR(255),                -- 제조회사
    image_url TEXT,                           -- 상품 이미지 URL
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 3. 제휴 보험 전용 상품 관리 테이블
CREATE TABLE insurance_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL,            -- 보험 종류
    name VARCHAR(255) NOT NULL,               -- 보험명
    price INTEGER NOT NULL,                   -- 보험료
    company VARCHAR(255),                     -- 보험회사
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 인덱스 추가 (조회 성능 최적화)
CREATE INDEX idx_admin_stats_date ON admin_daily_stats(stats_date);
CREATE INDEX idx_partner_product_cat ON partner_products(category);
CREATE INDEX idx_insurance_product_cat ON insurance_products(category);

-- 4. 관리자 문의 내역 테이블
CREATE TABLE admin_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_admin_inquiry_created ON admin_inquiries(created_at);
