CREATE TABLE jwt_refresh_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    refresh VARCHAR(512) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_jwt_refresh_entity PRIMARY KEY (id)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users (
    id UUID NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    signup_provider VARCHAR(50),
    nickname VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    withdrawn_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    role_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE user_profiles (
    user_id UUID NOT NULL,
    birth_year SMALLINT,
    gender VARCHAR(10),
    region_code VARCHAR(20),
    marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_id),
    CONSTRAINT fk_user_profiles_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE user_terms_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    terms_code VARCHAR(50) NOT NULL,
    agreed BOOLEAN NOT NULL DEFAULT TRUE,
    agreed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    method TEXT NOT NULL,
    client_platform TEXT NOT NULL,
    CONSTRAINT pk_user_terms_agreements PRIMARY KEY (id),
    CONSTRAINT fk_user_terms_agreements_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_user_terms_agreements_user_code UNIQUE (user_id, terms_code)
);

INSERT INTO roles (name) VALUES ('USER'), ('ADMIN');