CREATE TABLE ai_check_sessions (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    status TEXT NOT NULL,
    client_meta_json JSONB,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_check_sessions PRIMARY KEY (id),
    CONSTRAINT fk_ai_check_sessions_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE ai_images (
    id UUID NOT NULL,
    session_id UUID NOT NULL,
    image_url TEXT NOT NULL,
    image_hash VARCHAR(64),
    taken_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_images PRIMARY KEY (id),
    CONSTRAINT fk_ai_images_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id)
);

CREATE TABLE ai_image_quality (
    id UUID NOT NULL,
    image_id UUID NOT NULL,
    is_pass BOOLEAN NOT NULL,
    fail_reason TEXT,
    score NUMERIC(6, 3),
    detail_json JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_image_quality PRIMARY KEY (id),
    CONSTRAINT uc_ai_image_quality_image UNIQUE (image_id),
    CONSTRAINT fk_ai_image_quality_image FOREIGN KEY (image_id) REFERENCES ai_images (id)
);

CREATE TABLE ai_detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id UUID NOT NULL,
    image_id UUID NOT NULL,
    model_name VARCHAR(50) NOT NULL,
    label TEXT NOT NULL,
    confidence NUMERIC(6, 4) NOT NULL,
    bbox_x NUMERIC(8, 6) NOT NULL,
    bbox_y NUMERIC(8, 6) NOT NULL,
    bbox_w NUMERIC(8, 6) NOT NULL,
    bbox_h NUMERIC(8, 6) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_detections PRIMARY KEY (id),
    CONSTRAINT fk_ai_detections_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id),
    CONSTRAINT fk_ai_detections_image FOREIGN KEY (image_id) REFERENCES ai_images (id)
);

CREATE TABLE ai_risk_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id UUID NOT NULL,
    model_name VARCHAR(50) NOT NULL,
    target TEXT NOT NULL,
    pred_class TEXT NOT NULL,
    score NUMERIC(6, 4) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_risk_scores PRIMARY KEY (id),
    CONSTRAINT fk_ai_risk_scores_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id)
);

CREATE TABLE ai_reports (
    id UUID NOT NULL,
    session_id UUID NOT NULL,
    summary TEXT NOT NULL,
    routine_guide TEXT NOT NULL,
    warnings TEXT,
    disclaimer_version VARCHAR(30),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_reports PRIMARY KEY (id),
    CONSTRAINT uc_ai_reports_session UNIQUE (session_id),
    CONSTRAINT fk_ai_reports_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id)
);