-- 1. 병원 도메인 테이블 생성
CREATE TABLE hospitals (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(50),
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    homepage_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hospitals PRIMARY KEY (id)
);

CREATE TABLE user_hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    hospital_id UUID NOT NULL,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    last_visit_date TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_hospitals PRIMARY KEY (id),
    CONSTRAINT fk_user_hospitals_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_hospitals_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT uq_user_hospitals_user_hospital UNIQUE (user_id, hospital_id)
);

-- 2. AI 리포트 테이블 재생성 (User Custom Schema 적용)
-- 기존 데이터가 있다면 백업하거나 삭제해야 함. 여기서는 개발 단계라 가정하고 재생성.
DROP TABLE IF EXISTS ai_reports;

CREATE TABLE ai_reports (
    id UUID NOT NULL DEFAULT gen_random_uuid (),
    session_id UUID NOT NULL,
    summary TEXT NOT NULL,
    details TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'ko',
    disclaimer_version VARCHAR(30) DEFAULT 'v1.0',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_ai_reports PRIMARY KEY (id),
    CONSTRAINT fk_ai_reports_check_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id),
    CONSTRAINT uc_ai_reports_session UNIQUE (session_id)
);

-- 3. AI 의사결정 기록 테이블 생성
CREATE TABLE ai_decision_records (
    id UUID NOT NULL DEFAULT gen_random_uuid (),
    session_id UUID NOT NULL,
    decision_json JSONB NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    model_versions JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_ai_decision_records PRIMARY KEY (id),
    CONSTRAINT fk_ai_decision_records_session FOREIGN KEY (session_id) REFERENCES ai_check_sessions (id),
    CONSTRAINT uc_ai_decision_records_session UNIQUE (session_id)
);

-- 4. 인덱스 추가
CREATE INDEX idx_ai_reports_session ON ai_reports (session_id);

CREATE INDEX idx_ai_decision_records_session ON ai_decision_records (session_id);